# Generated by Django 3.0.8 on 2020-07-10 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='guardianPhoneNumber',
            field=models.DecimalField(decimal_places=0, max_digits=15),
        ),
    ]
