# Generated by Django 3.0.8 on 2020-07-15 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_auto_20200710_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='profileImage',
            field=models.ImageField(blank=True, default='media/Anonymous-Avatar.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='student',
            name='profileImage',
            field=models.ImageField(blank=True, default='media/Anonymous-Avatar.png', null=True, upload_to=''),
        ),
    ]
